[package]
name = "har"
version = "0.3.0"
authors = ["Sebastian Mandrean <sebastian.mandrean@gmail.com>"]
edition = "2018"
description = "A HTTP Archive format (HAR) serialization & deserialization library."
license = "MIT"
repository = "https://github.com/mandrean/har-rs"
documentation = "https://docs.rs/har"
readme = "README.md"
keywords = ["har", "serialization", "deserialization", "json", "yaml"]

[badges]
travis-ci = { repository = "mandrean/har-rs" }

[dependencies]
error-chain = "0.12.0"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"
serde_yaml = "0.8.7"
semver = "0.9.0"
url = "1.7.2"
url_serde = "0.2.0"

[dev-dependencies]
glob = "0.3.0"
